# Generated by Django 5.0.4 on 2024-05-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonoregalo',
            name='reserva',
        ),
        migrations.AddField(
            model_name='bonoregalo',
            name='apellidos_receptor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bonoregalo',
            name='nombre_receptor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bonoregalo',
            name='valor',
            field=models.PositiveIntegerField(choices=[(50, '50 €'), (80, '80 €'), (100, '100 €')], default=50),
        ),
    ]
