# Generated by Django 5.0.4 on 2024-05-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_bonoregalo_reserva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonoregalo',
            name='email_receptor',
        ),
    ]
