# Generated by Django 5.0.4 on 2024-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_images',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to='img/'),
        ),
    ]
