# Generated by Django 5.0.4 on 2024-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_images',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
