# Generated by Django 5.0.4 on 2024-06-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customuser_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='Reservado', max_length=20),
        ),
        migrations.CreateModel(
            name='HorarioSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.saladekaraoke')),
            ],
            options={
                'db_table': 'horario_sala',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.horariosala'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('sala', 'horario')},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora',
        ),
    ]
