# Generated by Django 5.0.4 on 2024-06-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_horariosala_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonoregalo',
            options={'verbose_name': 'Bono', 'verbose_name_plural': 'Bonos'},
        ),
        migrations.AlterModelOptions(
            name='horariosala',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='saladekaraoke',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AddField(
            model_name='horariosala',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='horariosala',
            name='dia',
            field=models.CharField(default='Miércoles', max_length=20),
        ),
    ]
