"""
Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u-rkhow(ybsru!tgn&20@qh7ee!w)1()ca$-2)7g6%1&(-*=om'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['07ee-37-10-139-163.ngrok-free.app', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Lista de orígenes permitidos para solicitudes CORS.
CORS_ALLOWED_ORIGINS = [
    "https://07ee-37-10-139-163.ngrok-free.app",
]

# Definimos una lista de orígenes confiables para la protección CSRF.
CSRF_TRUSTED_ORIGINS = [
    'https://07ee-37-10-139-163.ngrok-free.app',
]

ROOT_URLCONF = 'proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'sqlite3.db',                      # Or path to database file if using sqlite3.
        'USER': '',                      # Not used with sqlite3.
        'PASSWORD': '',                  # Not used with sqlite3.
        'HOST': '',                      # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '',                      # Set to empty string for default. Not used with sqlite3.
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# https://docs.djangoproject.com/en/5.0/howto/static-files/

# URL base para acceder a los archivos estáticos
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Archivos estáticos (CSS, JavaScript, Imágenes)
STATIC_URL = '/static/'
# Directorio de archivos estáticos
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Archivos de medios (Subidos por los usuarios)
MEDIA_URL = '/media/'   # URL base para acceder a los archivos de medios
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')    # Directorio donde se almacenan los archivos de medios en el sistema de archivos


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Backends de autenticación
AUTHENTICATION_BACKENDS = [
    'core.backends.EmailBackend',   # Backend personalizado para autenticación por email
    'django.contrib.auth.backends.ModelBackend',    # Backend estándar de Django
]

# URL para la página de inicio de sesión
LOGIN_URL = 'core:login'
# URL para redirigir después de iniciar sesión
LOGIN_REDIRECT_URL = 'core:indice'
# URL para redirigir después de cerrar sesión
LOGOUT_REDIRECT_URL = 'core:indice'

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'core.CustomUser'     # Especifica el modelo de usuario personalizado
